// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApiAuthCheck(arg1) {
  return window['go']['ui']['App']['ApiAuthCheck'](arg1);
}

export function ApiOnvifDeviceProfile(arg1, arg2) {
  return window['go']['ui']['App']['ApiOnvifDeviceProfile'](arg1, arg2);
}

export function ApiOnvifDevicePtzMoveAbsolute(arg1, arg2) {
  return window['go']['ui']['App']['ApiOnvifDevicePtzMoveAbsolute'](arg1, arg2);
}

export function ApiOnvifDevicePtzMoveRelative(arg1, arg2) {
  return window['go']['ui']['App']['ApiOnvifDevicePtzMoveRelative'](arg1, arg2);
}

export function ApiOnvifDevicePtzStatus(arg1, arg2) {
  return window['go']['ui']['App']['ApiOnvifDevicePtzStatus'](arg1, arg2);
}

export function ApiOnvifDeviceStreamurl(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['ui']['App']['ApiOnvifDeviceStreamurl'](arg1, arg2, arg3, arg4, arg5);
}

export function ApiOnvifDevices(arg1) {
  return window['go']['ui']['App']['ApiOnvifDevices'](arg1);
}

export function ApiOnvifPlay(arg1, arg2) {
  return window['go']['ui']['App']['ApiOnvifPlay'](arg1, arg2);
}
