desc = "qonvif"
debug = true

[server]
host = "127.0.0.1"
port = 8373
api_key = "123456"

[[devices]]
name = "Living"
device = { host = "", port = 80, username = "admin", password = "" }

[player]
path = ""
